(async () => {

    const rp = require("request-promise");
    const endpoint = "http://localhost:8040/ipfs-store";

    // **********************************************************************************************************
    //Store a JSON document on IPFS:
    console.log("### Store blog post on IPFS")
    const example = {
        "title": "My first Blog post",
        "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        "author": "greg",
        "category": "Life",
        "date_created": "2018-01-01T20:00:00Z",
        "version": 1
    }

    var result = await rp({
        "uri": endpoint + "/json/store",
        "method": "POST",
        "json": example
    });
    console.log(result); // { hash: "QmfPYmF66GUD6CueKbDAFMneSoJzRKnCKeVDXbTV68bxMo" }


    // **********************************************************************************************************
    // Index in ElasticSearch
    console.log("### Index blog post")
    const indexRequestExample = {
        "index"         : "blog_post", // Name of the index
        "id"            : "blog_post_01", // if null - autogenerated
        "content_type"  : "application/json", 
        "hash"          : "QmfPYmF66GUD6CueKbDAFMneSoJzRKnCKeVDXbTV68bxMo", 
        "index_fields"  : [
            {
                "name": "title",
                "value": example.title
            },
            {
                "name": "author",
                "value": example.author
            },
            {
                "name": "category",
                "value": example.category
            },
            {
                "name": "date_created",
                "value": example.date_created
            },
            {
                "name": "version",
                "value": example.version
            }
        ]
    }

    var result = await rp({
        uri: endpoint + "/json/index",
        method: "POST",
        json: indexRequestExample
    });
    console.log(result); // { index: "blog_post", id: "blog_post_01", hash: "QmfPYmF66GUD6CueKbDAFMneSoJzRKnCKeVDXbTV68bxMo" }


    // **********************************************************************************************************
    // store & Index in a row
    console.log("### store & Index in a row")
    const storeIndexRequestExample = {
        "payload"   : {
            "title": "My first Blog post",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "author": "greg",
            "category": "Life",
            "date_created": "2018-01-01T20:00:00Z",
            "version": 1
        },
        "index": "blog_post",
        "id": "blog_post_01", // if null - autogenerated
        "content_type": "application/json",
        "index_fields": [
            {
                "name": "title",
                "value": example.title
            },
            {
                "name": "author",
                "value": example.author
            },
            {
                "name": "category",
                "value": example.category
            },
            {
                "name": "date_created",
                "value": example.date_created
            },
            {
                "name": "version",
                "value": example.version
            }
        ]
    }

    var result = await rp({
        "uri": endpoint + "/json/store_index",
        "method": "POST",
        "json": storeIndexRequestExample
    });
    console.log(result); // { index: "blog_post", id: "blog_post_01", hash: "QmfPYmF66GUD6CueKbDAFMneSoJzRKnCKeVDXbTV68bxMo" }
 


    // **********************************************************************************************************
    // Get a document by hash
    console.log("### Get a document by hash")
    var result = await rp({
        "uri": endpoint + "/query/fetch/QmdFuipjKprVXAbdpEE577wUXteC4X8CTgiGXiJzWFB88s",
        "method": "GET"
    });
    console.log(result); // {"title":"My first Blog post","content":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry"s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","author":"greg","category":"Life"}

    // **********************************************************************************************************
    // Search
    console.log("### Search")
    var result = await rp({
        "uri"   : endpoint + "/query/search?index=blog_post",
        "method": "POST",
        "json": {

        }
    });
    console.log(result); // { content:  [ { index: 'blog_post', id: 'blog_post_01', hash: 'QmdFuipjKprVXAbdpEE577wUXteC4X8CTgiGXiJzWFB88s', content_type: 'application/json', index_fields: [Array] } ], totalPages: 1, numberOfElements: 1, firstPage: true, lastPage: true, sort: null, totalElements: 1, size: 20, number: 0 }



})();
