package net.consensys.gjeanmart;

import java.io.IOException;
import java.math.BigInteger;
import java.util.Arrays;
import java.util.Collections;

import org.junit.Test;
import org.web3j.abi.FunctionEncoder;
import org.web3j.abi.TypeReference;
import org.web3j.abi.datatypes.Function;
import org.web3j.abi.datatypes.Type;
import org.web3j.crypto.Credentials;
import org.web3j.crypto.RawTransaction;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.DefaultBlockParameterName;
import org.web3j.protocol.core.methods.response.EthGetTransactionCount;
import org.web3j.protocol.core.methods.response.EthSendTransaction;
import org.web3j.protocol.core.methods.response.Web3ClientVersion;
import org.web3j.protocol.http.HttpService;
import org.web3j.tx.ChainId;
import org.web3j.tx.RawTransactionManager;
import org.web3j.tx.TransactionManager;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class TestCounter {

    @Test
    public void test() throws Exception {

        final String privateKey = "48c2210576121c68883b2f96ae82cdf5fd845d99f4243b9c44651316accaac97";
        final String contractAddress = "0x5e417E6d4e15471912743e1173D5fD3a3617aD9f";
        final BigInteger gasLimit = new BigInteger("6721975");
        final BigInteger gasPrice = new BigInteger("20000000000");
        
        // Connect to the node
        Web3j web3 = Web3j.build(new HttpService());  // defaults to http://localhost:8545/

        // Read Private Key
        Credentials credentials = Credentials.create(privateKey);
        
        // Extract the  function from the Smart Contract wrapper generated by web3j cli
        final Function function = new Function(
                Counter.FUNC_INCREMENT, 
                Arrays.<Type>asList(), 
                Collections.<TypeReference<?>>emptyList());
        
        // Encode to data
        String data = FunctionEncoder.encode(function);
        
        // Calculate nonce
        EthGetTransactionCount ethGetTransactionCount = web3.ethGetTransactionCount(credentials.getAddress(), DefaultBlockParameterName.PENDING).send();
        BigInteger nonce =  ethGetTransactionCount.getTransactionCount();
        
        // Prepare transaction
        RawTransaction rawTransaction = RawTransaction.createTransaction(
                nonce,
                gasPrice,
                gasLimit,
                contractAddress,
                BigInteger.ZERO,
                data);
        
        // Transaction manager
        RawTransactionManager transactionManager = new RawTransactionManager(web3, credentials);
        EthSendTransaction transaction = transactionManager.signAndSend(rawTransaction);
        
        log.debug("transaction hash = {}", transaction.getTransactionHash());
        
        //////////////////////////

        Thread.sleep(2000);
        
        // Load contract
        Counter contract = Counter.load(contractAddress, web3, credentials, gasLimit, gasLimit);
        
        BigInteger counter = contract.getCounter().send();
        log.info("counter = " + counter.intValue());
        
    }
    
}
